services:
  - type: web
    name: inventory-management
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
  
  - type: pserv
    name: inventory-db
    env: postgresql
    plan: free
    databaseName: inventory_management
    user: inventory_user